/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HangmanDriver */

#ifndef _Included_HangmanDriver
#define _Included_HangmanDriver
#ifdef __cplusplus
extern "C" {
#endif
#undef HangmanDriver_MIN_PRIORITY
#define HangmanDriver_MIN_PRIORITY 1L
#undef HangmanDriver_NORM_PRIORITY
#define HangmanDriver_NORM_PRIORITY 5L
#undef HangmanDriver_MAX_PRIORITY
#define HangmanDriver_MAX_PRIORITY 10L
/*
 * Class:     HangmanDriver
 * Method:    clear_screen_win_api
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HangmanDriver_clear_1screen_1win_1api
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
